### ISSUE TITLE
When a user other than administrator try to see a tree view, gets: "TypeError: Cannot read property 'appendTo' of undefined"

### ISSUE THREAD

**Issue by Danisan** [antonioburic/addons-infoterra#1]
http://localhost:8069/web/content/3358-eb37900/web.assets_backend.js:3482
Rastreo de error:
TypeError: Cannot read property 'appendTo' of undefined
    at Class.renderSidebar (http://localhost:8069/web/content/3358-eb37900/web.assets_backend.js:3482:14)
    at Class.render_view_control_elements (http://localhost:8069/web/content/3358-eb37900/web.assets_backend.js:489:92)
    at Class._display_view (http://localhost:8069/web/content/3358-eb37900/web.assets_backend.js:483:266)
    at Object.<anonymous> (http://localhost:8069/web/content/3358-eb37900/web.assets_backend.js:482:49)
    at Object.<anonymous> (http://localhost:8069/web/content/3353-e1e2d89/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/3353-e1e2d89/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/3353-e1e2d89/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:8069/web/content/3353-e1e2d89/web.assets_common.js:803:56)
    at http://localhost:8069/web/content/3358-eb37900/web.assets_backend.js:481:373
    at fire (http://localhost:8069/web/content/3353-e1e2d89/web.assets_common.js:796:299)

**Comment by antonioburic** [comment]
@Danisan Hi Daniel, thanks for reporting - can you please share some more info on this case - does it happen for all tree views and is it done on the latest v11 code? I'm trying to reproduce it on my end, but can't.

**Comment by DelfosCloud** [comment]
Hola he encontrado cual es el incoveniente a este problema y lo he solucionado todo se debe al cierre de un bloque fuera de lugar.
adjunto archivo js con la solucion y agradesco el desarrollo del modulo.
##############################
odoo.define("web_disable_export_delete_button", function(require) {
"use strict";

    var core = require("web.core");
    var Sidebar = require('web.Sidebar');
    var ListController = require("web.ListController");
    var _t = core._t;
    var session = require("web.session");

    ListController.include({
        
    	/**
         * Render the sidebar (the 'action' menu in the control panel, right of the
         * main buttons)
         *
         * @param {jQuery Node} $node
         */
        renderSidebar: function ($node) {
            if (this.hasSidebar && !this.sidebar) {
            	
            	var has_export_group = false;
            	this.getSession().user_has_group('web_disable_export_delete_button.group_export_button').then(function(has_group) {
                    if(has_group) {
                    	has_export_group = true;
                    } else {
                    	has_export_group = false;
                    }
                });
                
                var has_delete_group = false;
            	this.getSession().user_has_group('web_disable_export_delete_button.group_delete_button').then(function(has_group) {
                    if(has_group) {
                    	has_delete_group = true;
                    } else {
                    	has_delete_group = false;
                    }
                });
                
                if (session.is_superuser) {
					has_export_group = true;
					has_delete_group = true;
				}
                    
				var other = [];
				
				if (has_export_group) {
					other.push({
						label: _t("Export"),
						callback: this._onExportData.bind(this)
					});
				}
				
				if (this.archiveEnabled) {
					other.push({
						label: _t("Archive"),
						callback: this._onToggleArchiveState.bind(this, true)
					});
					other.push({
						label: _t("Unarchive"),
						callback: this._onToggleArchiveState.bind(this, false)
					});
				}
				
				if (this.is_action_enabled('delete')) {
					
					if (has_delete_group) {
						other.push({
							label: _t('Delete'),
							callback: this._onDeleteSelectedRecords.bind(this)
						});
					}
				}					
                // este bloque se cerraba solo cuando se obtenia la opcion de delete bloque anterior.
                this.sidebar = new Sidebar(this, {
                    editable: this.is_action_enabled('edit'),
                    env: {
                        context: this.model.get(this.handle, {raw: true}).getContext(),
                        activeIds: this.getSelectedIds(),
                        model: this.modelName,
                    },
                    actions: _.extend(this.toolbarActions, {other: other}),
                });
                
            	this.sidebar.appendTo($node);	
				this._toggleSidebar();
            }
        }
    });
});
###################

**Comment by antonioburic** [comment]
thanks^^ it should be fixed now.
